export class CustomMap<K, V, IK=string> {
    // No open addressing or buckets.
    // Keys generated by converter must be unique.
    map: Map<IK, {key: K, value: V}> = new Map();
    converter: (key: K) => IK;

    constructor(converter: (key: K) => IK) {
        this.converter = converter;
    }

    set(key: K, value: V) {
        this.map.set(this.converter(key), {key: key, value: value});
    }

    get(key: K): V | undefined {
        return this.map.get(this.converter(key))?.value;
    }

    clear() {
        this.map.clear();
    }

    has(key: K): boolean {
        return this.map.has(this.converter(key));
    }

    remove(key: K): boolean {
        return this.map.delete(this.converter(key));
    }

    [Symbol.iterator]() {
        return this.map.values();
    }
};

export class CustomSet<K, IK=string> {
    map: CustomMap<K, K, IK>;
    constructor(converter: (key: K) => IK) {
        this.map = new CustomMap(converter);
    }

    static pairSet<T>(): CustomSet<[T, T]> {
        return new CustomSet(([a, b]) => a < b ? `${a}:${b}` : `${b}:${a}`);
    }

    add(key: K) {
        this.map.set(key, key);
    }

    remove(key: K): boolean {
        return this.map.remove(key);
    }

    has(key: K): boolean {
        return this.map.has(key);
    }

    clear() {
        this.map.clear();
    }

    [Symbol.iterator](): Iterator<K> {
        const itr = this.map.map.values();
        return {
            next: () => {
                const next = itr.next();
                if (next.done) {
                    return {value: undefined, done: true};
                }
                return {value: next.value.value, done: false};
            },
        };
    }
}